training:
  train_data_path: C:\Users\tangy\Downloads\DETR-GFTE\datasets\unified_train
  train_labels_path: C:\Users\tangy\Downloads\DETR-GFTE\datasets\unified_train.jsonl
  val_data_path: C:\Users\tangy\Downloads\DETR-GFTE\datasets\unified_val
  val_labels_path: C:\Users\tangy\Downloads\DETR-GFTE\datasets\unified_val.jsonl
  batch_size: 4
  num_epochs: 3